Repository googleapis/nodejs-os-config, pull requests merged in 2020-06, with the labels that each got.

#8 build: update protos.js
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#11 feat: move ts target to es2018 from es2016
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v1/os_config_service_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#14 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#15 fix: proper fallback option handling
  src/v1/os_config_service_client.ts
  synth.metadata
Labels: cla: yes, context: none

#16 feat: promote library to GA
  .repo-metadata.json
  README.md
  synth.metadata
Labels: automerge, cla: yes

#18 fix: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#20 docs: Fix several broken links in reference documentation
  protos/google/cloud/osconfig/v1/patch_deployments.proto
  protos/google/cloud/osconfig/v1/patch_jobs.proto
  synth.metadata
Labels: cla: yes, context: full

#21 build: add config .gitattributes
  .gitattributes
  .kokoro/.gitattributes
  synth.metadata
Labels: cla: yes, context: full
