Repository googleapis/nodejs-os-config, pull requests merged in 2020-11, with the labels that each got.

#57 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: osconfig, automerge, cla: yes, context: full

#58 build: add v1.OsConfigServiceClient type
  src/index.ts
  synth.metadata
Labels: api: osconfig, cla: yes, context: none

#59 fix: do not modify options object, use defaultScopes
  package.json
  src/v1/os_config_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: osconfig, automerge, cla: yes

#62 feat: Added PatchRollout feature to PatchDeployments inventory proto definitions for VM Manager Inventory
  protos/google/cloud/osconfig/v1/inventory.proto
  protos/google/cloud/osconfig/v1/osconfig_common.proto
  protos/google/cloud/osconfig/v1/patch_deployments.proto
  protos/google/cloud/osconfig/v1/patch_jobs.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/os_config_service_client.ts
  src/v1/os_config_service_proto_list.json
  synth.metadata
Labels: api: osconfig, cla: yes, context: partial

#68 build: update protos.json
  protos/protos.json
  src/v1/os_config_service_client.ts
  synth.metadata
Labels: api: osconfig, cla: yes, context: none

#69 fix: check for fetch on window
  src/v1/os_config_service_client.ts
  synth.metadata
Labels: api: osconfig, automerge, cla: yes, context: partial

#71 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: osconfig, automerge, cla: yes, context: full
